export interface QTSeekBarEvent {
  progress: number
}

export enum QTSeekBarGravity {
  QT_SEEK_BAR_GRAVITY_TOP = 0,
  QT_SEEK_BAR_GRAVITY_BOTTOM = 1,
  QT_SEEK_BAR_GRAVITY_CENTER = 2,
}

export enum QTSeekBarIndicatorMode {
  QT_SEEK_BAR_INDICATION_MODE_SHOW_WHEN_TOUCH = 0,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_HIDE = 1,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_SHOW_AFTER_TOUCH = 2,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_SHOW = 3,
}

export enum QTSeekBarMode {
  QT_SEEK_BAR_MODE_SINGLE = 1,
  QT_SEEK_BAR_MODE_RANGE = 2,
}

export enum QTSeekBarTickMarkGravity {
  QT_SEEK_BAR_TICK_MARK_GRAVITY_LEFT = 0,
  QT_SEEK_BAR_TICK_MARK_GRAVITY_CENTER = 1,
  QT_SEEK_BAR_TICK_MARK_GRAVITY_RIGHT = 2,
}

export enum QTSeekBarTickMarkLayoutGravity {
  QT_SEEK_BAR_TICK_MARK_LAYOUT_GRAVITY_TOP = 0,
  QT_SEEK_BAR_TICK_MARK_LAYOUT_GRAVITY_BOTTOM = 1,
}

export enum QTSeekBarTickMarkMode {
  QT_SEEK_BAR_TICK_MARK_MODE_NUMBER = 0,
  QT_SEEK_BAR_TICK_MARK_MODE_OTHER = 1,
}
