name: Sync to Mirror Repo

on:
  push:
    branches:
      - main
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to another repo
        run: |

          git remote add mirror https://gitlab.extscreen.com/es/quicktvui-next.git
          git push --mirror mirror
